<template>
   <section class="bg-gray-800 xl:w-72">
    <div class="flex justify-between px-4 py-3 xl:hidden">
      <div class="relative m-w-xs w-full">
        <div class="absolute inset-y-0 left-0 flex items-center pl-3">
            <svg class="h-6 w-6 fill-current text-gray-600" version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
              <path d="M9.516 14.016q1.875 0 3.188-1.313t1.313-3.188-1.313-3.188-3.188-1.313-3.188 1.313-1.313 3.188 1.313 3.188 3.188 1.313zM15.516 14.016l4.969 4.969-1.5 1.5-4.969-4.969v-0.797l-0.281-0.281q-1.781 1.547-4.219 1.547-2.719 0-4.617-1.875t-1.898-4.594 1.898-4.617 4.617-1.898 4.594 1.898 1.875 4.617q0 0.984-0.469 2.227t-1.078 1.992l0.281 0.281h0.797z"></path>
            </svg>
        </div>
        <input class="rounded-lg w-full sm:w-auto block bg-gray-900 text-white px-10 py-2 focus:outline-none focus:bg-gray-200 focus:text-gray-900 pl-10 pr-4 py-2" type="text" placeholder="Search By Keywords">
      </div>
      <button 
        @click="toggle" 
        :class="{
          'bg-gray-600': isOpen, 
          'bg-gray-700' : !isOpen
        }" 
        class="ml-4 inline-flex rounded-lg  hover:bg-gray-600 pl-3 pr-4 focus:outline-none focus:shadow-outline">
        <!-- Generated by IcoMoon.io -->
        <svg class="h-6 w-6 fill-current text-gray-500" version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
          <path d="M6 12.984v-1.969h12v1.969h-12zM3 6h18v2.016h-18v-2.016zM9.984 18v-2.016h4.031v2.016h-4.031z"></path>
        </svg>
        <span class="text-white ml-1 font-medium">
          Filters
        </span>
      </button>
     </div>
     <form v-show="isOpen" class="xl:flex xl:flex-col xl:justify-between xl:h-full">
       <div class="lg:flex xl:block xl:overflow-y-auto">
        <div class="px-4 py-4 border-t border-gray-900 lg:w-1/3 xl:w-full">
          <div class="flex flex-wrap -mx-2">
            <label class="block w-1/2 px-2 sm:w-1/4 lg:w-1/2">
              <span class="text-sm font-semibold text-gray-500">Bedrooms</span>
              <select class="form-select mt-1 w-full block text-white">
                <option value="4">4</option>
              </select>
            </label>
            <label class="block w-1/2 px-2 sm:w-1/4 lg:w-1/2">
              <span class="text-sm font-semibold text-gray-500">Bathrooms</span>
              <select class="form-select mt-1 w-full block text-white">
                <option value="2">2</option>
              </select>
            </label>
            <label class="block w-full mt-4 px-2 sm:w-1/2 sm:mt-0 lg:w-full">
              <span class="text-sm font-semibold text-gray-500">Price Range</span>
              <select class="mt-1 block w-full form-select block text-white">
                <option value="1">Up to $2 000 /wk</option>
              </select>
            </label>
          </div>
          
          
        </div>
        <div class="py-4 px-4 border-t lg:border-l border-gray-900 lg:w-1/3 xl:w-full">
          <span class="text-sm font-semibold text-gray-500">Property Type</span>
          <div class="sm:flex sm:-mx-2 lg:block">
            <label class="block mt-3 sm:w-1/4 sm:px-2 flex items-center lg:px-0">
              <input class="form-radio" type="radio" name="propertyType" value="house">
              <span class="ml-2 text-white">House</span>
            </label>
            <label class="block mt-3 sm:w-1/4 sm:px-2 flex items-center lg:px-0">
                <input class="form-radio" type="radio" name="propertyType" value="apartment">
                <span class="ml-2 text-white">Apartment</span>
            </label>
              <label class="block mt-3 sm:w-1/4 sm:px-2 flex items-center lg:px-0">
              <input class="form-radio" type="radio" name="propertyType" value="loft">
              <span class="ml-2 text-white">Loft</span>
            </label>
              <label class="block mt-3 sm:w-1/4 sm:px-2 flex items-center lg:px-0">
              <input class="form-radio" type="radio" name="propertyType" value="townhouse">
              <span class="ml-2 text-white">Townhouse</span>
            </label>
          </div>
        </div>
        <div class="py-4 px-4 border-t lg:border-l border-gray-900 lg:w-1/3 xl:w-full">
          <span class="text-sm font-semibold text-gray-500">Amenities</span>
          <div class="sm:flex sm:-mx-2 sm:flex-wrap">
            <label class="block mt-3 sm:px-2 sm:w-1/4 lg:w-1/2 lg:px-0 xl:w-full">
              <input class="form-checkbox" type="checkbox" name="balcony">
              <span class="ml-2 text-white">Balcony</span>
            </label>
            <label class="block mt-3 sm:px-2 sm:w-1/4 lg:w-1/2 lg:px-0 xl:w-full">
              <input class="form-checkbox" type="checkbox" name="pool">
              <span class="ml-2 text-white">Pool</span>
            </label>
            <label class="block mt-3 sm:px-2 sm:w-1/4 lg:w-1/2 lg:px-0 xl:w-full">
              <input class="form-checkbox" type="checkbox" name="beach">
              <span class="ml-2 text-white">Beach</span>
            </label>
            <label class="block mt-3 sm:px-2 sm:w-1/4 lg:w-1/2 lg:px-0 xl:w-full">
              <input class="form-checkbox" type="checkbox" name="kf">
              <span class="ml-2 text-white">Kid Friendly</span>
            </label>
            <label class="block mt-3 sm:px-2 sm:w-1/4 lg:w-1/2 lg:px-0 xl:w-full">
              <input class="form-checkbox" type="checkbox" name="pf">
              <span class="ml-2 text-white">Pet Friendly</span> 
            </label>
            <label class="block mt-3 sm:px-2 sm:w-1/4 lg:w-1/2 lg:px-0 xl:w-full">
              <input class="form-checkbox" type="checkbox" name="packing">
              <span class="ml-2 text-white">Parking</span> 
            </label>
            <label class="block mt-3 sm:px-2 sm:w-1/2 lg:w-3/4 lg:px-0">
              <input class="form-checkbox" type="checkbox" name="ac">
              <span class="ml-2 text-white">Air Conditioning</span> 
            </label>
          </div>
        </div>
       </div>
       <div class="bg-gray-900 px-4 py-4 sm:text-right">
         <button class="block sm:w-auto sm:inline-block w-full px-4 py-2 font-semibold rounded-lg hover:bg-indigo-400 bg-indigo-500 text-white xl:block xl:w-full">Update Results</button>
       </div>
     </form>
   </section>
</template>

<script>
export default {
  data() {
    return {
      isOpen: true 
    }
  },

  methods: {
    toggle() {
      this.isOpen = !this.isOpen
    }
  }

}
</script>